config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :users
  get "/login" => "sessions#login"
  post"/login" => "sessions#create"
  get "/register" =>"users#new"
  delete "/logout" =>"sessions#destroy"
  resources :users, only:[:show] do
      resources :transcations, only: [:index, :new, :show, :create, :destroy]
  end
  resources :transactions, only: [:index] #temporary to get basic server running. 
  root to: 'sessions#login'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :transactions
    has_many :users, through: :transactions
end

app/models/transaction.rb
class Transaction < ApplicationRecord
    belongs_to :user
    belongs_to :item
end

app/models/transcation.rb
class Transcation < ApplicationRecord
    belongs_to :user
    belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
   has_many :transactions
   has_many :items, through: :transactions
   has_secure_password

   def self.admin_users
     where(is_admin: true)
   end

   def allow_admin_registration=(set = false)
      self.allow_admin_registration = set
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def index
        @items = Item.all
    end
    def new
    end
    def create
    end
    def show
    end 
    def edit
    end
    def update
    end
    def destroy
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    layout "form-layout", only: :login
    
    def login
        if current_user
            flash[:alert] = "you are already logged in"
            redirect_to user_path(current_user)
        end
    end

    def create
        user = User.find_by(username: params[:user][:username])
        if user.try(:authenticate, params[:user][:password])
            session[:user_id] = user.id 
            redirect_to user_path(user)
        else
            flash[:error] ="Invalid login details, please try again"
            redirect_to login_path
        end
    end
    def destroy
        session.delete :user_id
        reset_user
        redirect_to login_path
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
    
    def index
        @transactions=Transaction.all
    end

    def new
    end
    def show
    end
    def create
    end
    def destroy
    end
end

app/controllers/transcations_controller.rb
class TranscationsController < ApplicationController
    def index
        @transactions.all
    end
    def new
    end
    def show
    end
    def create
    end
    def destroy
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    layout "home", only: [:show]
    def index
     if admin?
        @users = User.all
     elsif current_user
        flash[:error] = "admins only"
        redirect_to user_path(current_user)
     else 
        flash[:error] ="please login"
        redirect_to login_path
     end

    end
    
    def new
        if admin?
            @user = User.new
        elsif current_user
            flash[:error] = "admins only"
            redirect_to user_path(current_user)
        elsif User.admin_users
            @user = User.new
            allow_admin_registration = false
        else
            @user = User.new
            allow_admin_registration = true
        end
    end

    def show
        @user = User.find_by(id: params[:id])
    end

    def edit
    end
    def create
        user = User.new(user_params)
        if user.save
            session[:user_id] = user.id
            redirect_to user_path(user)
        else
            render :new
        end
    end

    def update
    end
    def destroy
    end
    private
        def user_params
            params.require(:user).permit(:username, :name, :password,:password_confirmation,:is_admin)
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user #returns user object or nil
        if session[:user_id]
            @c_user ||= User.find_by(id: session[:user_id])
        else
            @c_user = nil
        end
        @c_user  
    end

    def reset_user
        @c_user =nil
    end
    def admin?
        current_user.try(:is_admin)
    end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/items/_item-form.html.erb
<%=form_for @item do |u|%>
<%=u.label :name %>
<%=u.text_field :name %>
<%=u.label :description %>
<%=u.text_field :description%>
<%=u.label :price%>
<%=u.number_field :price%>
<%=u.label :quantity%>
<%=u.number_field :quantity%>
<%=u.label :restock_level%>
<%=u.number_field :restock_level%>
<%=u.label :expirey_date%>
<%=u.date_field :expirey_date%>
<%=u.submit%>
<%end%>

app/views/items/edit.html.erb
<h1>Edit <%=@item.name%></h1>
<%= render "item-form"%>

app/views/items/index.html.erb
<%@items.each do |item| %>
<%= link_to item.name, item_path(item) %>
<%end%>

app/views/items/new.html.erb
<h1>Create Item</h1>
<%= render "item-form"%>

app/views/items/show.html.erb
<h1><%=@item.id %></h1>
<h1><%=@item.name %></h1>
<h1><%=@item.description %></h1>
<h1><%=@item.price %></h1>
<h1><%=@item.quantity %></h1>
<h1><%=@item.restock_level %></h1>
<h1><%=@item.expirey_date %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Stock Control</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%if current_user %>
      <nav id='menu'>
      <input type='checkbox' id='responsive-menu' onclick='updatemenu()'><label></label>
      <ul>
        <li><%=link_to "Home", user_path(current_user) %></li>
        <li><a class='dropdown-arrow x' href=''>Items</a>
          <ul class='sub-menus'>
            <li><%=link_to "add to inventory", new_item_path%></li>
            <li><%=link_to "manage items", items_path%></li>
          </ul>
        </li>
        <li><a class='dropdown-arrow x' href=''>Transactions</a>
          <ul class='sub-menus'>
            <li><%=link_to"My Transactions", user_transcations_path(current_user) %></li>
            <li><%=link_to"Manage Transactions", transactions_url %></li>
          </ul>
        </li>
        <li><a class='dropdown-arrow x' href=''>Admin</a>
          <ul class='sub-menus'>
            <li><%=link_to "Manage Users",users_path%></li>
            <li><%=link_to "Manage My Profile",edit_user_path(current_user)%></li>
          </ul>
        </li>
        <li><%=button_to "Log out", logout_path, method: "delete", class: 'btn' %><li>
      </ul>
    </nav>
<%end%>
    <!-- content -->
    <div>
      <%=flash[:error] if flash[:error]%>
      <%=flash[:alert] if flash[:alert]%>
      <%=flash[:message] if flash[:message]%>
    </div>
              <%= yield %>
    <div class="footer">
        copyright OisagiTech: created by Arnold Bwaila
    </div>  
  </body>
</html>

app/views/layouts/form-layout.html.erb
<html>
  <head>
    <title>Rails Stock Control</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'form-layout', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
     <%= yield %>

    <div class="footer">
        copyright OisagiTech: created by Arnold Bwaila
    </div>  
  </body>
</html>

app/views/layouts/home.html.erb
<%= render template: "layouts/application" %>
 

app/views/transactions/index.html.erb
<%@transactions.each do |transaction| %>
<%= link_to transaction.type, transaction_path(transaction) %>
<%end%>

app/views/transactions/new.html.erb
<%=form_for @transaction do |u|%>
<%=u.label :user_id %>
<%=u.number_field :user_id %>
<%=u.label :item_name %>
<%=u.select_tag :item_name, options_from_collection_for_select(Item.all, :id, :name), include_blank: "Select Items"%>
<%=u.label :tr_qty, "Quantity"%>
<%=u.number_field :tr_qty%>
<%=u.label :tr_value,"Value"%>
<%=u.number_field :tr_value%>
<%=u.submit%>
<%end%>

app/views/transactions/show.html.erb
<h1><%=@transaction.id %></h1>
<h1><%=@transaction.user.name %></h1>
<h1><%=@transaction.item.name %></h1>
<h1><%=@transaction.type %></h1>

app/views/users/_user-form.html.erb
        <div class="content">
            <%=form_for @user do |u|%>
            <%=u.label :username %><br/>
            <%=u.text_field :username %><br/>
            <%=u.label :name %><br/>
            <%=u.text_field :name%><br/>
            <%=u.label :password%><br/>
            <%=u.password_field :password%><br/>
            <%=u.label :password_confirm%><br/>
            <%=u.password_field :password_confirm%><br/>
            <%if allow_admin_registration%>
                <%=u.label :is_admin%>
                <%=u.check_box :is_admin,
            <%=u.submit%>
            <%end%>
        </div>
    

app/views/users/edit.html.erb
<div class="wrapper">
    <div class="header">
        <h3>Edit: <%=@user.username%></h3>
    </div>
    <%=render "user-form"%>
</div>

app/views/users/index.html.erb
<%@users.each do |user| %>
<li> <%= link_to user.name, user_path(user) %></li>
<%end%>

app/views/users/new.html.erb
<div class="wrapper">
    <div class="header">
        <h3>Create New User</h3>
    </div>
    <%=render "user-form"%>
</div>

app/views/users/show.html.erb
<h1>Welcome <%=@user.name%></h1>
<div class="colmid">
    <div class="colleft">
        <div class="col1">
            <h3>Controls</h3>
            <%=link_to "Sell an Item",new_user_transcation_path(@user)%><br/>
            <%=link_to "Refund an Item",new_user_transcation_path(@user)%><br/>
            <%=link_to "Restock an Item",new_user_transcation_path(@user)%><br/>
        </div>
        <div class="col2">
            <h3>Reports</h3>
            <%=link_to "Items", user_transcations_path(@user)%><br/>
            <%=link_to "Transactions", user_transcations_path(@user)%><br/><br/>
        </div> 
        <div class="col3">
            <h3>Admin</h3>
            <%=link_to "Edit My Profile",edit_user_path(@user)%><br/>
            <%=link_to "Manage Items",items_path%><br/>
            <%=link_to "Manage Transactions", transactions_path%><br/>
        </div> 
    </div> 
</div>